# File: .github/workflows/repo-sync.yml
name: Repo-Sync

on:
  schedule:
  - cron:  "27 */3 * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "graemeg/lazarus"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
